### PR TITLE
Version 4.0.4

### PR DESCRIPTION
**Pull request by andrewkcarter**
# For the Reviewer
- [ ] Code review complete
- [ ] Testing Complete
- [ ] Quality ORT App Documentation Updated (your name is in the Validator square for this feature)

When this is complete, you should approve the PR via github.

# For the Reviewee

<Reminder PR Title should be JIRA_NUMBER and Useful Description>

## Summary
Description of changes.

#### Release Note
<Concise sentence describing change>Required.

#### Breaking Changes
<Description for Techops of how to handle changes, migrations, updates>None.

## Quality Assurance

You have gathered the following items:
- [ ] This PR is tagged with a Release Milestone
- [ ] You have a log message clearly identifying when this feature is **working successfully**
- [ ] You have a log message clearly identifying when this feature is **failing**
- [ ] You added a PR against [p4-alerting](https://github.com/istresearch/p4-alerting/) to trigger based on the failure condition above

Given all of the items above, you have updated your Application ORT at the following locations:
- **Features and Alerting**: <link to app ORT>Required.
- **P4 Alerting**: <link to p4-alerting PR>Required.

## Testing and Verification

*Steps to test your application for someone not familiar with it.* Required.

1. Do this: `$ run-this.sh`
2. Look for this.
3. Clean up with this command

### CODE REVIEW

**Review by baracudda — APPROVED** [review]

**Review by baracudda — CHANGES_REQUESTED** [review]
shouldn't this be 4.0.5?

**Comment by andrewkcarter** [comment]
@baracudda it was never set to 4.0.4, so for the release PR this needs to be 4.0.4. After we merge the release PR, we'll roll all these to 4.0.5.

**Review by baracudda — APPROVED** [review]
I don't understand the comment, but willing to go along with it. As long as one of us knows what they're doing, that's fine.

**Comment by andrewkcarter** [comment]
The current version on this develop branch is 4.0.3.1. This PR makes it 4.0.4 so that we can make the 4.0.4 release. That's all.

**Pull request merged**
